### ISSUE TITLE
Please update your module version to Minecraft 1.20!

### ISSUE THREAD

**Issue by surfishs** [gbl/ClickThrough#24]
Please update your module version to Minecraft 1.20!

**Comment by Mudxiej** [comment]
I'm waiting here too

**Comment by histefanhere** [comment]
For anyone else that comes here, it's unlikely that there'll be an update to this mod in a while if ever. The creator has put the mod on hold and wrote this on it's [modrinth page](https://modrinth.com/mod/clickthrough):

> I haven't played Minecraft since 1.16, but I kept my mods updated because people wanted them. Unfortunately, Minecraft changed a lot of internals with 1.19.4, and updating isn't just a matter of changing a few things, it'll also mean figuring out a lot about how it works now. I currently don't have the time and energy to do this, so there won't be a 1.19.4 update in the forseeable future. Sorry for that to everybody who uses my mods.

**Comment by Ash-ex** [comment]
The mod works on 1.20

**Comment by histefanhere** [comment]
> The mod works on 1.20

Not quite, the game crashes when you right click a sign on a chest with the following error:

```
[14:55:27] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'net.minecraft.class_2561 net.minecraft.class_2625.method_30843(int, boolean)'
	at de.guntram.mcmod.clickthrough.ClickThrough.getSignRowText(ClickThrough.java:27) ~[clickthrough-1.19.3-fabric0.68.1-0.4.jar:?]
	at net.minecraft.class_310.handler$zzk000$clickthrough$switchCrosshairTarget(class_310.java:3555) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1583(class_310.java:1772) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2052) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1883) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

Minecraft 1.20 introduced a feature where you can right click signs to edit their text, or right click them with a honeycomb in your had to prevent the text from being edited further. I suspect this is conflicting with ClickThrough in some way. It's also not immediately clear what behaviour should be triggered when you right click a sign on a chest, because now there's two possible actions - editing the sign or opening the chest.

Tested on:
- Minecraft 1.20.1
- clickthrough-1.19.3-fabric0.68.1-0.4.jar
- fabric-api-0.83.1+1.20.1.jar
- fabric loader minecraft-1.20.1-0.14.21

**Comment by Mudxiej** [comment]
I just hope that somebody could do the fork for this mod so everyone is happy

**Comment by Berringer** [comment]
A new mod is released, does the same thing from what the description say. 
Will try it soon! Forge & Fabric 1.20
https://modrinth.com/mod/click-through-architectury

Edit: Works like a charm!

**Comment by Mudxiej** [comment]
> A new mod is released, does the same thing from what the description say. Will try it soon! Forge & Fabric 1.20 https://modrinth.com/mod/click-through-architectury
> 
> Edit: Works like a charm!

U R a legend!

**Comment by BertyBriker** [comment]
> A new mod is released, does the same thing from what the description say. Will try it soon! Forge & Fabric 1.20 https://modrinth.com/mod/click-through-architectury
> 
> Edit: Works like a charm!

It doesn't exist. How can I find it? Please, share the file or the new link. Thank you!

Edit: Why closed the topic, hello? The problem isn't solved. So ignorant!

**Comment by Slooshie1** [comment]
https://modrinth.com/mod/clickthrough-continued/version/1.20.1-fabric0.83.0-0.41

**Comment by The-Noah** [comment]
The mod appears to be updated on Modrinth: https://modrinth.com/mod/clickthrough/version/1.20-fabric0.83.0-0.4.1

**Comment by gbl** [comment]
> 
> Edit: Why closed the topic, hello? The problem isn't solved. So ignorant!

Friend, you're getting this for free. I made this mod when I was actually using it myself, and I maintained it for quite a while after I stopped playing MC (so it stopped being useful to me). You're not paying me for it, there is no entitlement at all to get updates.  Closing a topic with a "won't update any more" is a perfect means to tell people that, well, there won't be any more updates.

I did decide to update once again because some people were asking me nicely, but for the future: If you get somebody's work for free, and that person says they don't want to work for free anymore, calling them ignorant is not a good way to change their mind.

**Comment by KingofMidnight** [comment]
will there be a update soon for 1.20.2? also Thank u for making this Great Mod and i love using your mods they are Super useful

**Comment by Slooshie1** [comment]
The mod is already updated to 1.20.2

**Comment by KingofMidnight** [comment]
> The mod is already updated to 1.20.2


??? where and when?
![image_2023-11-19_192553196](https://github.com/gbl/ClickThrough/assets/57202402/f3a1bf21-0397-47e3-b0fc-174069fd9cce)

**Comment by Slooshie1** [comment]
You're looking at it. Install the 1.20.1 version. By the way I would recommend getting stuff from modrinth instead of curseforge

**Comment by KingofMidnight** [comment]
> You're looking at it. Install the 1.20.1 version. By the way I would recommend getting stuff from modrinth instead of curseforge

yeah i use modrinth but i couldn't get the snip of it, but are u sure the 1.20.1 version will work on 1.20.2?

**Comment by Slooshie1** [comment]
Im currently using it so yes

**Comment by KingofMidnight** [comment]
ah ok
